### ISSUE TITLE
OS X does not have htole64().

### ISSUE THREAD

**Issue by textbrowser** [tbuktu/libntru#14]
Please apply the following changes to poly.c.

--- a/libNTRU/src/poly.c
+++ b/libNTRU/src/poly.c
@@ -8,6 +8,11 @@
 #include "err.h"
 #include "arith.h"
 
+#ifdef __APPLE__
+#include <libkern/OSByteOrder.h> 
+#define htole64(x) OSSwapHostToLittleInt64(x)
+#endif
+
 #define NTRU_SPARSE_THRESH 20

**Comment by textbrowser** [comment]
GitHub is misinterpreting underscores.

underscoreunderscoreAPPLEunderscoreunderscore

**Comment by textbrowser** [comment]
And on a Windows 7 machine.

src/poly.c:679:9: warning: implicit declaration of function 'htole64' [-Wimplicit-function-declaration]
a64[i] = htole64(a64[i]);
^
gcc -g -O2 -Wall -Wextra -Wno-unused-parameter -shared -o libntru.dll src/bitstring.o src/encparams.o src/hash.o src/idxgen.o src/key.o src/mgf.o src/ntru.o src/poly.o src/rand.o src/arith.o src/sha1.o src/sha2.o -lws2_32 -ladvapi32
src/poly.o: In function `ntru_to_arr_64':
D:\datawin\spoton7git\spot-on\libNTRU/src/poly.c:679: undefined reference to `htole64'
collect2.exe: error: ld returned 1 exit status

**Comment by tbuktu** [comment]
Yeah, MinGW doesn't have htole64(), either. I pushed a fix.
Thanks for reporting this!

**Comment by Ivoz** [comment]
@textbrowser see the **code** tab on [this page](https://guides.github.com/features/mastering-markdown/) for how to paste code correctly in github comments / issues.

**Comment by textbrowser** [comment]
Thank you for the link.
