### ISSUE TITLE
equals_params()

### ISSUE THREAD

**Issue by textbrowser** [tbuktu/libntru#16]
I think I'm experiencing undesired behavior with tests/test_util.c on Windows XP. In equals_params(), two function pointers are being compared. The pointers are not equal when compared even if the DLL function pointer and the non-DLL function pointer refer to the same function.

Please see http://www-01.ibm.com/support/knowledgecenter/SSLTBW_1.12.0/com.ibm.zos.r12.cbcpx01/fpc.htm%23fpc.

Something unrelated. Should ntru_params_from_priv_key() copy the sparse field?

Thanks.

**Comment by tbuktu** [comment]
sparse isn't used. I need to delete it.

**Comment by tbuktu** [comment]
It's gone.
