### ISSUE TITLE
Quick patch to compile with old glibc < 2.9

### ISSUE THREAD

**Issue by lulol** [tbuktu/libntru#23]
--- src/poly.c.orig     Sun Sep  6 12:55:00 2015
+++ src/poly.c  Thu Sep 10 14:36:38 2015
@@ -19,6 +19,12 @@
 #define htole32(x) (x)
 #endif
 
+#if GLIBC <= 2 || ( GLIBC == 2 && GLIBC_MINOR < 9 )
+/* assume little endian */
+#define htole64(x) (x)
+#define htole32(x) (x)
+#endif
+
 #ifdef __OS2__
 #include <endian.h>
 #endif

**Comment by tbuktu** [comment]
Thanks, I'll take a look at it later this week.

**Comment by tbuktu** [comment]
Thank you!
