### ISSUE TITLE
Not an issue. Confused.

### ISSUE THREAD

**Issue by textbrowser** [tbuktu/libntru#27]
The function ntru_rand_tern() in src/poly.c uses at most half of rand_data in the first loop. The second loop also uses at most half of rand_data. Should ```if (r_idx >= rand_len)``` be ```if (r_idx >= 2 * rand_len)```?

**Comment by tbuktu** [comment]
Yes, it looks like half of the buffer is being wasted. I'll fix it when I have some time.

**Comment by tbuktu** [comment]
Actually, it wasn't wasting random data but the buffer was bigger than it needed to be.
