### ISSUE TITLE
PowerPC

### ISSUE THREAD

**Issue by textbrowser** [tbuktu/libntru#28]
Please modify src/poly.c

```
#ifdef __GLIBC__
#if __GLIBC__ <= 2 || ( __GLIBC__ == 2 && __GLIBC_MINOR__ < 9 )
/* assume little endian */
#ifndef __powerpc__
#define htole64(x) (x)
#define htole32(x) (x)
#endif
#endif
#endif
```

**Comment by Ivoz** [comment]
@textbrowser have you thought of submitting your contributions as pull requests?

**Comment by textbrowser** [comment]
Yup. :o)

**Comment by tbuktu** [comment]
The test_encr_decr test still fails. I'll have to look into it.

**Comment by textbrowser** [comment]
It may be. We need another Big Endian machine.

**Comment by textbrowser** [comment]
```valid &= memcmp(digest, digest_expected, 20) == 0;``` from test_encr_decr_det() fails.

**Comment by tbuktu** [comment]
Thank you for reporting this!
