### ISSUE TITLE
NTRU_AVOID_HAMMING_WT_PATENT

### ISSUE THREAD

**Issue by rubdos** [tbuktu/libntru#30]
> NTRU's main strengths are high performance and resistance to quantum computer attacks. Its main drawback is that it is patent encumbered. The patents expire in 2021; when built with the NTRU_AVOID_HAMMING_WT_PATENT flag, libntru becomes patent-free in 2017.

Would you mind explaining/documenting what this `NTRU_AVOID_HAMMING_WT_PATENT` flag changes?

Thank you!

**Comment by tbuktu** [comment]
It excludes the product-form code and all parameter sets that require it. So with ```NTRU_AVOID_HAMMING_WT_PATENT```, you only get the 12 parameter sets that become patent-free in 2017 but not the 6 that will be encumbered until 2021. I'll mention it in the README.
