### ISSUE TITLE
Plan to implement NTRUSign?

### ISSUE THREAD

**Issue by mlmikael** [tbuktu/libntru#32]
Hi!

What about API:s for making NTRU-based signatures?

It's in the Java variant currently but not here.

Thanks,
Mlmikael

**Comment by rubdos** [comment]
> What about API:s for making NTRU-based signatures?

NTRUSign is [considered broken by most](https://en.wikipedia.org/wiki/NTRUSign#Security).

**Comment by mlmikael** [comment]
Ah, thank you very much for pointing this out.

So then, conceptually, "NTRU Prime" (https://ntruprime.cr.yp.to/ntruprime-20160511.pdf) and "Sphincs-256", are those the only useful post-quantum signatures around?


Do you know any C library implementation of Sphincs-256? A Sphincs-256 implementation is dug down in SUPERCOP's sourcecode but that is a monolithic testing suite, not a library. Also what about NTRU Prime signatures, or any other ueful tool.

**Comment by rubdos** [comment]
> are those the only useful post-quantum signatures around?

If you cannot use a MAC, I suppose so. There's always [SIDH, which also has proposed signature schemes](https://en.wikipedia.org/wiki/Supersingular_isogeny_key_exchange#Similar_systems.2C_signatures.2C_and_uses).

**Comment by mlmikael** [comment]
SIDH looks dusty.

Hm. How would you do post-quantum sgnatures using MAC:s (libsodium-supported or not)?

**Comment by rubdos** [comment]
> SIDH looks dusty.

Underdeveloped at least.

> Hm. How would you do post-quantum sgnatures using MAC:s (libsodium-supported or not)?

[Apparently, HMAC's are safe](https://crypto.stackexchange.com/questions/7866/which-mac-scheme-is-quantum-resistant), so if you can live with the symmetry of such authentication, I suppose it suffices.

**Comment by tbuktu** [comment]
Yes, NTRUSign is dead which is why libntru doesn't implement it.
